"""
Django settings for conf project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

import logging
from opentelemetry import trace
from opentelemetry._logs import set_logger_provider
from opentelemetry.exporter.otlp.proto.grpc._log_exporter import OTLPLogExporter
from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, ConsoleSpanExporter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-CHANGE_ME")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG',default="false").lower() in ('true', 't', 'yes', 'y', '1', 1)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'apps.demo',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'
ASGI_APPLICATION = 'conf.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASE_URL = os.environ.get('DATABASE_URL', '') # example: postgres://postgres:postgres@localhost:5432/data
pattern = r'postgres://(?P<user>[^:]+):(?P<password>[^@]+)@(?P<host>[^:]+):(?P<port>\d+)/(?P<name>\w+)' # pylint: disable=invalid-name
matches = re.match(pattern, DATABASE_URL)
if matches:
    DATABASES = {
        'default': {
            'ENGINE': 'django_prometheus.db.backends.postgresql',
            'NAME': matches.group('name'),
            'USER': matches.group('user'),
            'PASSWORD': matches.group('password'),
            'HOST': matches.group('host'),
            'PORT': matches.group('port'),
        },
        'test': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': f"test_{os.environ.get('DB_NAME', default='data')}",
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# opentelemetry settings
OTEL_ENABLED = os.environ.get("OTEL_ENABLED", "false").lower() in ('true', 't', 'yes', 'y', '1', 1)
OTEL_PYTHON_DJANGO_INSTRUMENT = os.environ.get("OTEL_PYTHON_DJANGO_INSTRUMENT", "false").lower() in ('true', 't', 'yes', 'y', '1', 1)
OTEL_SERVICE_NAME = os.environ.get("OTEL_SERVICE_NAME", "signoz-poc-django-app")
OTEL_SERVICE_VERSION = os.environ.get("OTEL_SERVICE_VERSION", "0.0.1")
OTEL_TRACES_EXPORTER = os.environ.get("OTEL_TRACES_EXPORTER", "console,otlp")
OTEL_METRICS_EXPORTER = os.environ.get("OTEL_METRICS_EXPORTER", "console,otlp")
OTEL_LOGS_EXPORTER = os.environ.get("OTEL_LOGS_EXPORTER", "console,otlp")
OTEL_EXPORTER_OTLP_ENDPOINT = os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT", "localhost:4317")
OTEL_EXPORTER_OTLP_PROTOCOL = os.environ.get("OTEL_EXPORTER_OTLP_PROTOCOL", "grpc")
OTEL_RESOURCE_ATTRIBUTES = os.environ.get("OTEL_RESOURCE_ATTRIBUTES", f"service.name={OTEL_SERVICE_NAME},service.version={OTEL_SERVICE_VERSION}")

if OTEL_ENABLED:
    otlp_logger_provider = LoggerProvider(
        resource=Resource.create(
            {
                "service.name": OTEL_SERVICE_NAME,
                "service.version": OTEL_SERVICE_VERSION,
                "service.instance.id": os.getpid(),
            }
        ),
    )
    set_logger_provider(otlp_logger_provider)
    otlp_exporter = OTLPLogExporter(
        endpoint=OTEL_EXPORTER_OTLP_ENDPOINT,
        insecure=True  # Set to False if using HTTPS
    )
    otlp_logger_provider.add_log_record_processor(
        BatchLogRecordProcessor(otlp_exporter)
    )
    otlp_handler = LoggingHandler(
        level=logging.NOTSET, 
        logger_provider=otlp_logger_provider
    )
    otlp_logger = logging.getLogger("django.otlp")
    otlp_logger.setLevel(logging.DEBUG)
    otlp_logger.addHandler(otlp_handler)


# Logging configuration for Django
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'otlp': {
            'class': 'opentelemetry.sdk._logs.LoggingHandler',
            'level': 'DEBUG',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.otlp': {
            'handlers': ['console', 'otlp'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
if OTEL_ENABLED:
    LOGGING ['handlers']['otlp']['logger_provider'] = otlp_logger_provider