helmDefaults:
  kubeContext: kind-signoz
  atomic: true
  verify: false
  wait: true
  timeout: 96000
  force: false
  createNamespace: true

repositories:
  - name: signoz
    url: https://charts.signoz.io
  - name: clickhouse-operator
    url: https://docs.altinity.com/clickhouse-operator/
  - name: clickhouse
    url: https://helm.altinity.com
  - name: opentelemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
releases:
  - name: clickhouse-operator
    namespace: clickhouse
    chart: clickhouse-operator/altinity-clickhouse-operator
    version: 0.25.6
    values:
      - operator.yaml
  - name: clickhouse
    namespace: clickhouse
    chart: clickhouse/clickhouse
    version: 0.3.7
    values:
      - clickhouse.yaml
  - name: signoz
    namespace: signoz
    chart: signoz/signoz
    version: 0.104.1
    values:
      - signoz.yaml
  - name: signoz-infra
    namespace: signoz
    chart: signoz/k8s-infra
    version: 0.15.0
    values:
      - signoz-infra.yaml
  - name: sample
    namespace: sample
    chart: ./chart/itscontained
    values:
      - sample.yaml
  # - name: demo
  #   namespace: test
  #   chart: opentelemetry/opentelemetry-demo
  #   version: 0.38.6
  #   values:
  #     - demo.yaml
  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.24.1
  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.24.1
    values:
      - istio-istiod.yaml
  - name: gateway
    namespace: istio-system
    chart: istio/gateway
    version: 1.24.1
    values:
      - istio-gateway.yaml
  - name: istio-extras
    namespace: istio-system
    chart: ./chart/itscontained
    values:
      - istio-extras.yaml
